"""add new usertopic relation that was missing

Revision ID: 32669cd1ab59
Revises: 361867dc6b3a
Create Date: 2024-05-01 15:15:58.270802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32669cd1ab59'
down_revision = '361867dc6b3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_topics',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'topic_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_topics')
    # ### end Alembic commands ###
