"""add category column to Note model

Revision ID: 675985852adc
Revises: b1cabefdff36
Create Date: 2024-04-28 16:19:03.492430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675985852adc'
down_revision = 'b1cabefdff36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False))

    with op.batch_alter_table('references', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('references', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
